# Generated by Django 5.2.1 on 2025-06-08 08:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPsot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('meta_description', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=155, unique=True, verbose_name='slug')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('PUBLISHED', 'Published'), ('IN_WORK', 'In work'), ('DELETED', 'Deleted')], default='In work', verbose_name='Post status')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoriesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WEB_DEVELOPMENT_SEO', ' Web Development & SEO'), ('ADVERTISING_PERFORMANCE', 'Advertising & Performance'), ('SMM', 'SMM'), ('AI_AUTOMATION', 'AI & Automation')], verbose_name='Category post name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
