# Generated by Django 5.2.1 on 2025-06-22 11:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WEB_DEVELOPMENT_SEO', 'Web Development & SEO'), ('ADVERTISING_PERFORMANCE', 'Advertising & Performance'), ('SMM', 'SMM'), ('AI_AUTOMATION', 'AI & Automation')], verbose_name='Category post name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/categories/images/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('meta_description', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=155, unique=True, verbose_name='slug')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('PUBLISHED', 'Published'), ('IN_WORK', 'In work'), ('DELETED', 'Deleted')], default='In work', verbose_name='Post status')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='blog.categories', verbose_name='Post category')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=155, null=True, unique=True, verbose_name='slug')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_category', to='blog.categories', verbose_name='Service category')),
            ],
        ),
    ]
