# Generated by Django 5.2.1 on 2025-06-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriespost',
            name='name',
            field=models.CharField(choices=[('Web Development & SEO', 'Web Development & SEO'), ('Advertising & Performance', 'Advertising & Performance'), ('SMM', 'SMM'), ('AI & Automation', 'AI & Automation')], verbose_name='Category post name'),
        ),
    ]
