# Generated by Django 5.2.1 on 2025-06-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_categoriespost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriespost',
            name='name',
            field=models.CharField(choices=[('WEB_DEVELOPMENT_SEO', 'Web Development & SEO'), ('ADVERTISING_PERFORMANCE', 'Advertising & Performance'), ('SMM', 'SMM'), ('AI_AUTOMATION', 'AI & Automation')], verbose_name='Category post name'),
        ),
    ]
