# Generated by Django 5.2.1 on 2025-06-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesPost',
            new_name='Categories',
        ),
    ]
