# Generated by Django 5.2.1 on 2025-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_categoriespost_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, max_length=155, null=True, unique=True, verbose_name='slug'),
        ),
    ]
