name: Django CI


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # только пуш в main
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build all images using docker-compose
        run: docker compose build

      - name: Push backend, nginx, celery and celery beat images
        run: |
          docker push valdemarbackend/yourtargetai-web
          docker push valdemarbackend/yourtargetai-nginx
          docker push valdemarbackend/yourtargetai-celery
          docker push valdemarbackend/yourtargetai-celery_beat

      - name: Pull & Push official Postgres and Redis
        run: |
          docker pull postgres:17
          docker tag postgres:17 valdemarbackend/yourtargetai-postgres:17
          docker push valdemarbackend/yourtargetai-postgres:17
  
          docker pull redis:7
          docker tag redis:7 valdemarbackend/yourtargetai-redis:7
          docker push valdemarbackend/yourtargetai-redis:7



  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up SSH VM and SSH for GitHub
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server pull code, clean up & restart
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          
          set -xe
    
          cd ~
    
          if [ ! -d "yourtarget/.git" ]; then
              rm -rf yourtarget
              git clone -b develop https://github.com/Volodymyr-tech/yourtarget.git yourtarget
            else
              cd yourtarget
              git pull origin develop
            fi
    
          sudo docker system prune -a --volumes -f || true
          sudo docker compose down --remove-orphans || true
          sudo docker compose up -d || true
          EOF